### PR TITLE
Added custom wrappers ability

### PR DESCRIPTION
**Pull request by Balamir**
Now, you can set any wrappers to the timer objects like hours, minutes,
seconds.

### CODE REVIEW

**Comment by o3bvv** [comment]
Hi, @Balamir

Thanks for your contribution, I'll try to check this as soon as possible. Could you please add missing line at the end of `custom.css` file meanwhile?

**Comment by Balamir** [comment]
Hi @oblalex 

Sorry for answering late. I fixed it.

Thanks.

**Comment by o3bvv** [comment]
Hi,

Thanks for that.

As for the solution, it seems to be a huge and inflexible overkill. You can do the same by specifying `format` and `value_setter: 'html'` parameters during initialization of timer.

Please, [checkout this example](https://jsfiddle.net/oblalex/fz2xhdfh/1/) and tell, if it covers your needs.

Thanks

**Comment by Balamir** [comment]
Hi @oblalex 

It is. I was missed that, sorry.

Thank you.

**Pull request closed without merging**
