### PR TITLE
included MIT-LICENSE.txt , project info and new events "on_start" , "on_cancel"

### PR DESCRIPTION
**Pull request by ltdeta**

### CODE REVIEW

**Comment by o3bvv** [comment]
Well, this looks much better :relieved: Thanks for including project info.

Some things which still need to be done:
- `.min.js` must be updated as well.
- It would be nice to put `LICENCE` file just near `README`.
- Docs and examples should be updated.

It would be great if you could do the first 2 steps also.

I'll be pleased to do the last step today in the evening. This requires a little update of examples and so on.

**Comment by ltdeta** [comment]
- step 1 (Which comressor should i use ?)

What do you mean by that **"It would be nice to put LICENCE file just near README."** ?
My intention (information inside the js file) was getting information about the plugin using it  in a project. because information about the plugin are not included in the js file (for eample version numer etc.) 
i can add a licence file something like that [MIT-LICENSE.txt](https://github.com/hekigan/is-loading/blob/master/MIT-LICENSE.txt)

**Comment by ltdeta** [comment]
done
- LICENCE file just near README.
- `.min.js` must be updated as well.
  => compressed with [uglifyjs](https://marijnhaverbeke.nl/uglifyjs)

**Comment by o3bvv** [comment]
I've used [jscompress](http://jscompress.com/) before, but this is not a big deal.

Everything seems to be OK. Thank you!

Im going to update the docs today a bit later.

**Comment by o3bvv** [comment]
Hi! Sorry for delay.

I've updated script a bit to prevent multiple clicks for `start` and `cancel` events.

Docs were also updated:
- [Handling start event](http://oblalex.github.io/jQuery-backward-timer/#handling-start-event).
- [Handling event of cancellation](http://oblalex.github.io/jQuery-backward-timer/#handling-event-of-cancellation).
- [Credits](http://oblalex.github.io/jQuery-backward-timer/#credits).

Thanks for your interest and help!

**Pull request merged**
